name: Build Latest TZDB

on:
  workflow_dispatch:
  push:
    branches:
      - main
#  schedule:
#    - cron: '0 0 * * *'

# $JAVA_HOME/lib/tzdb.dat

jobs:
  check:
    name: Check if newer version available
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Fetch latest version number from IANA
        run: wget https://data.iana.org/time-zones/tzdb/version
      - run : ls -la
      - name: Print versions
        run: echo "Latest IANA version `cat version` and Last processed version `cat last-processed-version`"
      - run: |
          IANA_VERSION=cat version | sed 's/ *//g'
          echo "::set-output name=content::$IANA_VERSION"
        id: IANA_VERSION
      - run: |
          LAST_PROCESSED_VERSION=cat last-processed-version | sed 's/ *//g'
          echo "::set-output name=content::$LAST_PROCESSED_VERSION"
        id: LAST_PROCESSED_VERSION
      - run: echo ${{steps.IANA_VERSION.outputs.content}} ${{steps.LAST_PROCESSED_VERSION.outputs.content}}
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: echo $JAVA_HOME
#      - run: which java
#      - run: which javac
#      - run: java -version
#      - run: javac -version
#      - run: head $JAVA_HOME/lib/tzdb.dat
#      - run: wget -O- https://apt.corretto.aws/corretto.key | sudo apt-key add - 
#      - run: sudo add-apt-repository 'deb https://apt.corretto.aws stable main'
#      - run: sudo apt-get update
#      - run: sudo apt-get install -y java-17-amazon-corretto-jdk
#      - run: ls -la /usr/lib/jvm/java-17-amazon-corretto
#      - run: sudo update-alternatives --set java "/usr/lib/jvm/java-17-amazon-corretto/bin/java"
#      - run: sudo update-alternatives --set javac "/usr/lib/jvm/java-17-amazon-corretto/bin/javac"
#      - run: export JAVA_HOME=/usr/lib/jvm/java-17-amazon-corretto
#      - run: wget https://data.iana.org/time-zones/tzdb/version
#      - run: cat version