name: Build Latest TZDB

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 0 * * *'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - run: wget -O- https://apt.corretto.aws/corretto.key | sudo apt-key add - 
      - run: sudo add-apt-repository 'deb https://apt.corretto.aws stable main'
      - run: sudo apt-get update
      - run: sudo apt-get install -y java-17-amazon-corretto-jdk
      - run: java -version